[package]
name = "identity"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "uuid", "macros", "migrate"] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "2"
serde = { version = "1.0.229", features = ["derive"] }